# .streamlit/secrets.toml

[passwords]
# Follow the rule: username = "password"
admin = "admin123"
brk = "brk8789"

[mysql]
host = "162.214.80.43"
port = 3306
user = "edureshu_examportal"
password = "Swrn@2022@"
database = "edureshu_examportal"